trivy  --format json --output trivy_security_scan_controller:stable-2.11.4.json image cr.l5d.io/linkerd/controller:stable-2.11.4
trivy  --format json --output trivy_security_scan_grafana:stable-2.11.4.json image cr.l5d.io/linkerd/grafana:stable-2.11.4
trivy  --format json --output trivy_security_scan_metrics-api:stable-2.11.4.json image cr.l5d.io/linkerd/metrics-api:stable-2.11.4
trivy  --format json --output trivy_security_scan_policy-controller:stable-2.11.4.json image cr.l5d.io/linkerd/policy-controller:stable-2.11.4
trivy  --format json --output trivy_security_scan_proxy:stable-2.11.4.json image cr.l5d.io/linkerd/proxy:stable-2.11.4
trivy  --format json --output trivy_security_scan_tap:stable-2.11.4.json image cr.l5d.io/linkerd/tap:stable-2.11.4
trivy  --format json --output trivy_security_scan_web:stable-2.11.4.json image cr.l5d.io/linkerd/web:stable-2.11.4
trivy  --format json --output trivy_security_scan_emojivoto-emoji-svc:v11.json image docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
trivy  --format json --output trivy_security_scan_emojivoto-voting-svc:v11.json image docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
trivy  --format json --output trivy_security_scan_emojivoto-web:v11.json image docker.l5d.io/buoyantio/emojivoto-web:v11
trivy  --format json --output trivy_security_scan_prometheus:v2.19.3.json image prom/prometheus:v2.19.3
trivy  --format table --output trivy_security_scan_controller:stable-2.11.4.txt image cr.l5d.io/linkerd/controller:stable-2.11.4
trivy  --format table --output trivy_security_scan_grafana:stable-2.11.4.txt image cr.l5d.io/linkerd/grafana:stable-2.11.4
trivy  --format table --output trivy_security_scan_metrics-api:stable-2.11.4.txt image cr.l5d.io/linkerd/metrics-api:stable-2.11.4
trivy  --format table --output trivy_security_scan_policy-controller:stable-2.11.4.txt image cr.l5d.io/linkerd/policy-controller:stable-2.11.4
trivy  --format table --output trivy_security_scan_proxy:stable-2.11.4.txt image cr.l5d.io/linkerd/proxy:stable-2.11.4
trivy  --format table --output trivy_security_scan_tap:stable-2.11.4.txt image cr.l5d.io/linkerd/tap:stable-2.11.4
trivy  --format table --output trivy_security_scan_web:stable-2.11.4.txt image cr.l5d.io/linkerd/web:stable-2.11.4
trivy  --format table --output trivy_security_scan_emojivoto-emoji-svc:v11.txt image docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
trivy  --format table --output trivy_security_scan_emojivoto-voting-svc:v11.txt image docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
trivy  --format table --output trivy_security_scan_emojivoto-web:v11.txt image docker.l5d.io/buoyantio/emojivoto-web:v11
trivy  --format table --output trivy_security_scan_prometheus:v2.19.3.txt image prom/prometheus:v2.19.3
